# Horizontal Pod Autoscaler (HPA) for Apache Deployment
# This HPA automatically scales the number of pods in the apache-deployment
# based on CPU utilization.

apiVersion: autoscaling/v2  # API version for HPA
kind: HorizontalPodAutoscaler  # Resource type

metadata:
  name: apache-hpa           # Name of the HPA resource
  namespace: apache          # Namespace where the HPA and deployment reside

spec:
  scaleTargetRef:
    apiVersion: apps/v1      # API version of the target resource
    kind: Deployment         # Target resource type (Deployment)
    name: apache-deployment  # Name of the target deployment

  minReplicas: 1             # Minimum number of pods
  maxReplicas: 10            # Maximum number of pods

  metrics:
    - type: Resource         # Metric type (Resource-based)
      resource:
        name: cpu            # Resource to monitor (CPU)
        target:
          type: Utilization  # Target type (percentage utilization)
          averageUtilization: 50  # Target average CPU utilization (%)